import { Inter } from "next/font/google";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import React from "react";
import NavbarComponent from "./components/NavbarComponent"; // Ensure correct import
import 'bootstrap/dist/css/bootstrap.min.css';
import Footer from "./components/Footer.js";
import './globals.css';


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <title>{metadata.title}</title>
        <meta name="description" content={metadata.description} />
      </head>
      <body className="page-background">
        <div className="">
          <NavbarComponent />
        </div>
        <div className="pt">
          <div className="">{children}</div>
        </div>
        <footer className="pt-5 ">
          <Footer/>
        </footer>
      </body>
    </html>
  );
}
